CREATE TABLE IF NOT EXISTS LOTE (
    ID_LOTE BIGINT NOT NULL,
    CNPJ_TRANSMISSAO VARCHAR(20) NOT NULL,
    DATA_TRANSMISSAO TIMESTAMP NOT NULL,
    NUM_RECIBO VARCHAR(15),
    XML_RETORNO blob(102400),
    DATA_PROC TIMESTAMP,
    PRIMARY KEY(ID_LOTE)
);

CREATE TABLE IF NOT EXISTS EMITENTE (
    ID_EMITENTE INTEGER NOT NULL,
    X_NOME VARCHAR(60) NOT NULL,
    X_FANT VARCHAR(60),
    X_LGR VARCHAR(60) NOT NULL,
    NRO VARCHAR(60) NOT NULL,
    X_CPL VARCHAR(60),
    X_BAIRRO VARCHAR(60) NOT NULL,
    C_MUN VARCHAR(7) NOT NULL,
    X_MUN VARCHAR(60) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    CEP VARCHAR(8),
    C_PAIS VARCHAR(4),
    X_PAIS VARCHAR(60),
    FONE VARCHAR(14),
    IE VARCHAR(14) NOT NULL,
    IEST VARCHAR(14),
    IM VARCHAR(15),
    CNAE VARCHAR(7),
    LOGOTIPO blob(8000),
    TP_DOCUMENTO_ENUM INTEGER NOT NULL,
    NR_DOCUMENTO VARCHAR(14) NOT NULL,
    REGIME_TRIBUTARIO VARCHAR(4) NOT NULL,
    VERSAO VARCHAR(60) NOT NULL DEFAULT '1.02',
    PRIMARY KEY(ID_EMITENTE),
    UNIQUE(NR_DOCUMENTO)
);

CREATE TABLE IF NOT EXISTS PROPRIEDADE (
    ID_PROPRIEDADE INTEGER NOT NULL,
    PROPRIEDADE_ENUM INTEGER NOT NULL,
    VALOR VARCHAR(255),
    ID_EMITENTE INTEGER NOT NULL,
    PRIMARY KEY (ID_PROPRIEDADE),
    FOREIGN KEY (ID_EMITENTE) REFERENCES EMITENTE(ID_EMITENTE) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE(PROPRIEDADE_ENUM,ID_EMITENTE)
);

CREATE TABLE IF NOT EXISTS GENERATOR (
    GEN_KEY VARCHAR(50) NOT NULL,
    GEN_VALUE INTEGER NOT NULL,
    PRIMARY KEY (GEN_KEY)
);

CREATE TABLE IF NOT EXISTS TRANSPORTADORA (
    ID_TRANSPORTADORA INTEGER NOT NULL,
    TP_DOCUMENTO_ENUM INTEGER,
    NR_DOCUMENTO VARCHAR(15),
    X_NOME VARCHAR(60) NOT NULL,
    IE VARCHAR(14),
    X_ENDER VARCHAR(60),
    UF VARCHAR(2),
    X_MUN VARCHAR(60),
    ID_EMITENTE INTEGER NOT NULL,
    VERSAO VARCHAR(60) NOT NULL DEFAULT '1.02',
    PRIMARY KEY(ID_TRANSPORTADORA),
    FOREIGN KEY (ID_EMITENTE) REFERENCES EMITENTE(ID_EMITENTE) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS PRODUTO (
    ID_PRODUTO INTEGER NOT NULL,
    C_PROD VARCHAR(60) NOT NULL,
    X_PROD VARCHAR(120) NOT NULL,
    C_EAN VARCHAR(14),
    NCM VARCHAR(8),
    EX_TIPI VARCHAR(3),
    GENERO VARCHAR(2),
    U_COM VARCHAR(6),
    C_EAN_TRIB VARCHAR(14),
    U_TRIB VARCHAR(6),
    V_UN_COM VARCHAR(17),
    V_UN_TRIB VARCHAR(17),
    Q_TRIB VARCHAR(20),
    ID_EMITENTE INTEGER NOT NULL,
    VERSAO VARCHAR(60) NOT NULL DEFAULT '1.02',
    PRIMARY KEY (ID_PRODUTO),
    FOREIGN KEY (ID_EMITENTE) REFERENCES EMITENTE(ID_EMITENTE) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE( ID_EMITENTE,C_PROD)
);

CREATE TABLE IF NOT EXISTS IPI (
    ID_IPI INTEGER NOT NULL,
    CL_ENQ VARCHAR(5),
    CNPJ_PROD VARCHAR(14),
    C_ENQ VARCHAR(3),
    ID_PRODUTO INTEGER NOT NULL,
    PRIMARY KEY (ID_IPI),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS ICMS (
    ID_ICMS INTEGER NOT NULL,
    ORIG VARCHAR(2),
    ID_PRODUTO INTEGER NOT NULL,
    CST VARCHAR(7) NOT NULL,
    MOD_BC VARCHAR(2),
    P_RED_BC VARCHAR(6),
    P_ICMS VARCHAR(6),
    MOD_BCST VARCHAR(2),
    P_MVAST VARCHAR(6),
    P_RED_BCST VARCHAR(6),
    P_ICMSST VARCHAR(6),
    MOT_DES_ICMS VARCHAR(2),
    P_BCOP VARCHAR(6),
    UFST VARCHAR(2),
    P_CRED_SN VARCHAR(6),
    PRIMARY KEY(ID_ICMS),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE(ID_PRODUTO,CST)
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    TP_DOCUMENTO_ENUM INTEGER,
    ID_CLIENTE INTEGER NOT NULL,
    NR_DOCUMENTO VARCHAR(14),
    X_NOME VARCHAR(60) NOT NULL,
    X_LGR VARCHAR(60),
    NRO VARCHAR(60),
    X_CPL VARCHAR(60),
    X_BAIRRO VARCHAR(60),
    X_MUN VARCHAR(60),
    C_MUN VARCHAR(7),
    UF VARCHAR(2),
    CEP VARCHAR(8),
    C_PAIS VARCHAR(4),
    X_PAIS VARCHAR(60),
    FONE VARCHAR(14),
    EMAIL VARCHAR(60),
    ID_EMITENTE INTEGER NOT NULL,
    IE VARCHAR(14),
    IESUF VARCHAR(9),
    VERSAO VARCHAR(60) NOT NULL DEFAULT '1.02',
    PRIMARY KEY(ID_CLIENTE),
    FOREIGN KEY (ID_EMITENTE) REFERENCES EMITENTE(ID_EMITENTE) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS PARAMETROS (
    PARAMETROS_ENUM INTEGER NOT NULL,
    VALOR VARCHAR(255),
    PRIMARY KEY(PARAMETROS_ENUM)
);

CREATE TABLE IF NOT EXISTS CERTIFICADO_INFO (
    ID_CERTIFICADO_INFO INTEGER NOT NULL,
    ID_EMITENTE INTEGER NOT NULL,
    ALIAS VARCHAR(255)NOT NULL,
    NOME VARCHAR(255)NOT NULL,
    AUTORIDADE_CERTIFICADORA VARCHAR(255)NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    CAMINHO VARCHAR(255) NOT NULL,
    TIPO_CERTIFICADO VARCHAR(2) NOT NULL,
    DATA_UTILIZACAO TIMESTAMP,
    DATA_VALIDADE TIMESTAMP NOT NULL,
    PRIMARY KEY(ID_CERTIFICADO_INFO),
    FOREIGN KEY (ID_EMITENTE) REFERENCES EMITENTE(ID_EMITENTE) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS NOTA_FISCAL (
    ID_NOTA_FISCAL BIGINT NOT NULL,
    NUMERO VARCHAR(9) NOT NULL,
    SERIE VARCHAR(3) NOT NULL,
    MODELO VARCHAR(2) NOT NULL,
    SITUACAO VARCHAR(100) NOT NULL,
    MES VARCHAR(2) NOT NULL,
    ANO VARCHAR(2) NOT NULL,
    TIPO_EMISSAO VARCHAR(100),
    DATA_EMISSAO TIMESTAMP,
    DATA_AUTORIZACAO TIMESTAMP,
    CODIGO_NUMERICO_CHAVE_ACESSO VARCHAR(9),
    DIGITO_CHAVE_ACESSO VARCHAR(1),
    AUTORIZACAO_EXPORTADA_XML char(1) NOT NULL DEFAULT '0',
    DOCUMENTO_DEST VARCHAR(14),
    UF_DEST VARCHAR(2),
    NUMERO_RECIBO VARCHAR(15),
    DANFE_IMPRESSO char(1) NOT NULL DEFAULT '0',
    DOC_XML blob(102400),
    DATA_SISTEMA TIMESTAMP,
    PROTOCOLO blob(102400),
    NUMERO_PROTOCOLO VARCHAR(15),
    DATA_PROTOCOLO TIMESTAMP,
    CODIGO_UF_EMITENTE VARCHAR(2) NOT NULL,
    ID_EMITENTE INTEGER NOT NULL,
    ID_LOTE BIGINT,
    CODIGO_ERRO VARCHAR(3),
    MENSAGEM_ERRO VARCHAR(255),
    VERSAO VARCHAR(10) NOT NULL,
    PRIMARY KEY(ID_NOTA_FISCAL),
    FOREIGN KEY (ID_LOTE) REFERENCES LOTE(ID_LOTE) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ID_EMITENTE) REFERENCES EMITENTE(ID_EMITENTE) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE(NUMERO,SERIE,ANO,ID_EMITENTE)
);

CREATE TABLE IF NOT EXISTS CANCELAMENTO (
    ID_NOTA_FISCAL BIGINT NOT NULL,
    NUMERO_PROTOCOLO VARCHAR(15) NOT NULL,
    PROTOCOLO blob(102400) NOT NULL,
    DATA_PROTOCOLO TIMESTAMP NOT NULL,
    CODIGO_ERRO VARCHAR(3),
    MENSAGEM_ERRO VARCHAR(255),
    JUSTIFICATIVA VARCHAR(255),
    PRIMARY KEY (ID_NOTA_FISCAL),
    FOREIGN KEY (ID_NOTA_FISCAL) REFERENCES NOTA_FISCAL(ID_NOTA_FISCAL) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS INUTILIZACAO (
    ID_INUTILIZACAO BIGINT NOT NULL,
    ID_EMITENTE INTEGER NOT NULL,
    SERIE VARCHAR(3) NOT NULL,
    NUMERO_INICIAL VARCHAR(9) NOT NULL,
    NUMERO_FINAL VARCHAR(9) NOT NULL,
    PROTOCOLO_XML blob(102400),
    DATA_INUTILIZACAO TIMESTAMP,
    PRIMARY KEY (ID_INUTILIZACAO),
    FOREIGN KEY (ID_EMITENTE) REFERENCES EMITENTE(ID_EMITENTE) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE(ID_EMITENTE,SERIE,NUMERO_INICIAL,NUMERO_FINAL)
);

CREATE TABLE IF NOT EXISTS PESQUISA (
    ID_PESQUISA INTEGER NOT NULL,
    CAMPO_ENUM INTEGER NOT NULL,
    VALOR VARCHAR(120),
    ID_EMITENTE INTEGER NOT NULL,
    TELA_ENUM INTEGER NOT NULL,
    PRIMARY KEY (ID_PESQUISA),
    FOREIGN KEY (ID_EMITENTE) REFERENCES EMITENTE(ID_EMITENTE) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE(ID_EMITENTE,CAMPO_ENUM,TELA_ENUM)
);

CREATE TABLE IF NOT EXISTS NUMERACAO (
    ID_NUMERACAO INTEGER NOT NULL,
    SERIE VARCHAR(3) NOT NULL,
    NUMERO VARCHAR(9) NOT NULL,
    ANO VARCHAR(2) NOT NULL,
    DATA_SISTEMA TIMESTAMP,
    ID_EMITENTE INTEGER NOT NULL,
    PRIMARY KEY (ID_NUMERACAO),
    FOREIGN KEY (ID_EMITENTE) REFERENCES EMITENTE(ID_EMITENTE) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE(SERIE,ANO,ID_EMITENTE)
);

CREATE TABLE IF NOT EXISTS CONTROLE_VERSAO (
    ID_CONTROLE_VERSAO INTEGER NOT NULL,
    NUM_VERSAO_ENUM INTEGER NOT NULL,
    DATA_VERSAO date NOT NULL,
    PRIMARY KEY (ID_CONTROLE_VERSAO),
    UNIQUE(NUM_VERSAO_ENUM)
);

CREATE TABLE IF NOT EXISTS EVENTO (
    ID_EVENTO BIGINT NOT NULL,
    ID_NOTA_FISCAL BIGINT NOT NULL,
    TP_EVENTO VARCHAR(7) NOT NULL,
    N_SEQ_EVENTO INT NOT NULL,
    DATA_EVENTO TIMESTAMP,
    NUM_PROTOCOLO VARCHAR(15),
    XML_PROC blob(102400) NOT NULL,
    DATA_REG_EVENTO TIMESTAMP,
    PRIMARY KEY(ID_EVENTO),
    FOREIGN KEY (ID_NOTA_FISCAL) REFERENCES NOTA_FISCAL(ID_NOTA_FISCAL) ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO CONTROLE_VERSAO(ID_CONTROLE_VERSAO,NUM_VERSAO_ENUM,DATA_VERSAO) VALUES(0,0,CURRENT_DATE);
INSERT INTO CONTROLE_VERSAO(ID_CONTROLE_VERSAO,NUM_VERSAO_ENUM,DATA_VERSAO) VALUES(1,1,CURRENT_DATE);
