<?php

require_once dirname(__FILE__) . '/../../scripts/DownloadJar.php';

/**
 * Test class for DownloadJar.
 * Generated by PHPUnit on 2012-10-04 at 11:36:05.
 */
class DownloadJarTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var DownloadJar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DownloadJar('../emissor_receita/emissorNFe.jnlp');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testRun()
    {
        $this->object->run();
        $this->assertTrue(true);
    }

}